Feature/mui v5
brightlayer-ui/react-cli-templates pull request #45
Opened 2022-03-14 17:40 UTC by bkarambe

#### Changes proposed in this Pull Request:
- Added mui v5 dependencies for all the templated

#### To Test:
- Create template projects using command 
- Update the brightlayer-ui node modules after migration to v5
- npx create-react-app myapp --template file:path

2022-03-15 12:51 UTC, jeffvg commented
looks like all the ```<hidden>``` components are deprecated and should use paper or box in all templates. 

Not 100% sure but the implementation of useStyles makeStyles theme needs updated to 
```const useStyles = makeStyles((theme: Theme) =>``` and not ```const useStyles = makeStyles((theme) =>```

@daileytj

2022-03-15 13:42 UTC, daileytj requested changes
@bkarambe, Lots of duplicate changes need to be made here. I commented on the first few and then threw some 👀's on the remaining. I'm sure you'll see the pattern of what you need to update

2022-03-15 13:42 UTC, daileytj commented on authentication-typescript/template.json
> +            "@brightlayer-ui/icons-mui": "^2.8.1",
You're still using Material-UI v4 based packages. Let's use the latest alpha @brightlayer-ui packages.

2022-03-15 13:42 UTC, daileytj commented on authentication-typescript/template/src/pages/home.tsx
> +    const xs = useMediaQuery(theme.breakpoints.down('sm'));
rename this variable to reflect what it's actually doing. If it's no longer responding at xs let's not call it xs.

2022-03-15 13:42 UTC, daileytj commented on authentication/template.json
> +            "@brightlayer-ui/icons-mui": "^2.8.1",
use latest @brightlayer-ui alpha packages

2022-03-15 13:42 UTC, daileytj commented on authentication/template/src/App.test.jsx
> +            <ThemeProvider theme={createTheme(adaptV4Theme(BLUIThemes.blue))}>
I don't think we need the v4 theme adapter if you use the latest alpha theme that was built for MUIv5

2022-03-15 13:42 UTC, daileytj commented on routing-typescript/template.json
> +            "@brightlayer-ui/icons-mui": "^2.8.1",
👀

2022-03-15 13:42 UTC, daileytj commented on routing/template/src/pages/home.jsx
> +    const xs = useMediaQuery(theme.breakpoints.down('sm'));
👀

2022-03-15 13:42 UTC, daileytj commented on routing/template/src/pages/home.jsx
> +                    <Hidden smDown>
deprecated 👀

2022-03-15 13:45 UTC, daileytj commented
You'll also need to update the CHANGELOG.md for each template as well as update the package version number. Probably best to make this a major update.

2022-03-15 13:50 UTC, daileytj commented
> looks like all the `<hidden>` components are deprecated and should use paper or box in all templates.
> 
> Not 100% sure but the implementation of useStyles makeStyles theme needs updated to `const useStyles = makeStyles((theme: Theme) =>` and not `const useStyles = makeStyles((theme) =>`
> 
> @daileytj

If it's typescript, the type will need to be explicitly set as it is not inferred for the theme. If it's a javascript template, we won't need it because there are no types/interfaces.

2022-03-17 06:56 UTC, ektasawant commented
1. Padding should be 16px as per current design
<img width="1351" alt="Screenshot 2022-03-17 at 12 07 42 PM" src="https://user-images.githubusercontent.com/10433274/158753252-650d5e5f-c07a-415b-a1ae-4dee949cc073.png">
2. DOM nesting error
<img width="559" alt="Screenshot 2022-03-17 at 11 54 34 AM" src="https://user-images.githubusercontent.com/10433274/158753285-d03fc76d-326b-45c4-9985-78a2096115d6.png">
3. dot appears in next line since <p> tag is used. In our current version we are using <span>.
<img width="836" alt="Screenshot 2022-03-17 at 11 54 39 AM" src="https://user-images.githubusercontent.com/10433274/158753291-14c57807-1001-4dde-b221-6c20a534fd01.png">

2022-03-17 11:51 UTC, ektasawant commented
Update Package.json with following:
1. @brightlayer-ui/react-themes@7.0.0-alpha.1
2. @brightlayer-ui/react-auth-workflow@3.0.0-alpha.0

2022-03-21 15:19 UTC, ektasawant commented
> 1. Padding should be 16px as per current design
> 
> <img alt="Screenshot 2022-03-17 at 12 07 42 PM" width="1351" src="https://user-images.githubusercontent.com/10433274/158753252-650d5e5f-c07a-415b-a1ae-4dee949cc073.png">
> 
> 2. DOM nesting error
> <img alt="Screenshot 2022-03-17 at 11 54 34 AM" width="559" src="https://user-images.githubusercontent.com/10433274/158753285-d03fc76d-326b-45c4-9985-78a2096115d6.png">
> 
> 3. dot appears in next line since
> tag is used. In our current version we are using . <img alt="Screenshot 2022-03-17 at 11 54 39 AM" width="836" src="https://user-images.githubusercontent.com/10433274/158753291-14c57807-1001-4dde-b221-6c20a534fd01.png">

Tested above fixes. Working fine 👍 .

2022-03-22 09:25 UTC, ektasawant approved these changes

2022-03-22 12:02 UTC, emclaug2 commented
I ran through these templates yesterday; looks good to me.  If you're happy with the changes @daileytj this should be good to go.

2022-03-22 12:22 UTC, emclaug2 approved these changes

2022-03-22 14:25 UTC, merged